default_configurations:
  locations:
    pitock:
      site_code: &site_code_pdx 'pdx'
      environment:
        development:
          site_code: *site_code_pdx
          domain: 'smarshdev.com'
          network: 'dev_pdx_linux_01' 
          #network_id: '65fb74bb-f72c-42a2-af63-9ba28cbe58f4'
        qa:
          site_code: *site_code_pdx
          domain: 'smarshqa.com'
          network: 'qa_pdx_linux_01'
          #          network_id: 'e6bf64d8-c407-499e-8096-54cc6aadc539'
    quincy:
      site_code: &site_code_qcy 'qcy'
      environment:
        site_code: *site_code_qcy
        development:
          domain: 'smarshdev.com'
          network: 'dev_pdx_linux_01'
    
host_definitions:
  m1.small_centos7:
    hostgroup: 'flavor:m1.small-centos7'
  webarchive_crawler:
    hostgroup: 'centos7'
    name: 'watest-%02d-%02d'
  webarchive_activemq:
    hostgroup: 'webarchive_activemq'
    name: 'waactivemq-%s-%s'
